# Generated by Django 5.1.5 on 2025-01-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
